import React, { useState } from "react";
import { Save, X } from "lucide-react";
import type { AppSettings, Mode, Notice, Reconciliation, SettingsData, Side, Trade, Workspace } from "./types";
import { apiPath, nowTime, request, today } from "./lib";
import { Card, Empty, Field, Modal, NumberField } from "./ui";

export function TradeModal({ mode, workspace: w, config, onClose, onMutate }: { mode: Mode; workspace: Workspace; config: { side: Side; code?: string; editing?: Trade }; onClose: () => void; onMutate: (p: Promise<Workspace>) => void }) {
  const edit = config.editing; const position = w.positions.find((p) => p.code === config.code);
  const [form, setForm] = useState({ code: edit?.code || config.code || "", name: edit?.name || position?.name || "", type: edit?.type || config.side, date: edit?.date || today(), time: edit?.time || nowTime(), price: String(edit?.price || position?.currentPrice || ""), quantity: String(edit?.quantity || (config.side === "SELL" ? position?.availableQuantity || "" : "")), reason: edit?.reason || "", remark: edit?.remark || "", historicalBackfill: edit?.historicalBackfill || false });
  const set = (key: string, value: unknown) => setForm((x) => ({ ...x, [key]: value }));
  const save = () => { const payload = { ...edit, ...form, accountMode: mode, price: Number(form.price), quantity: Number(form.quantity), amount: Number(form.price) * Number(form.quantity), commission: edit?.commission || 0, stampDuty: edit?.stampDuty || 0, transferFee: edit?.transferFee || 0, totalFee: edit?.totalFee || 0, rulesConclusion: edit?.rulesConclusion || "无法判断", violationTags: edit?.violationTags || [], manualFeeOverride: edit?.manualFeeOverride || false }; onMutate(request(apiPath(mode, edit ? `/trades/${edit.id}` : "/trades"), { method: edit ? "PUT" : "POST", body: JSON.stringify(payload) })); onClose(); };
  return <Modal title={`${mode === "real" ? "实盘记录" : "模拟训练"} · ${form.type === "BUY" ? "买入" : "卖出"}`} onClose={onClose}><div className="grid gap-3 sm:grid-cols-2"><Field label="方向"><select className="input" value={form.type} onChange={(e) => set("type", e.target.value)}><option value="BUY">买入</option><option value="SELL">卖出</option></select></Field><Field label="股票代码"><input className="input" value={form.code} onChange={(e) => set("code", e.target.value)} /></Field><Field label="股票名称"><input className="input" value={form.name} onChange={(e) => set("name", e.target.value)} /></Field><Field label="成交日期"><input type="date" className="input" value={form.date} onChange={(e) => set("date", e.target.value)} /></Field><Field label="成交时间"><input className="input" value={form.time} onChange={(e) => set("time", e.target.value)} /></Field><Field label="成交价格"><input type="number" step="0.01" className="input" value={form.price} onChange={(e) => set("price", e.target.value)} /></Field><Field label="成交数量"><input type="number" step="100" className="input" value={form.quantity} onChange={(e) => set("quantity", e.target.value)} /></Field><Field label="历史补录"><label className="flex h-10 items-center gap-2"><input type="checkbox" checked={form.historicalBackfill} onChange={(e) => set("historicalBackfill", e.target.checked)} />跳过当时余额和 T+1 校验</label></Field></div><Field label="交易依据/离场原因"><textarea className="input resize-none" rows={3} value={form.reason} onChange={(e) => set("reason", e.target.value)} /></Field><Field label="备注"><input className="input" value={form.remark} onChange={(e) => set("remark", e.target.value)} /></Field>{mode === "real" && <div className="rounded-xl border border-orange-900 bg-orange-950/30 p-3 text-xs text-orange-300">请核对同花顺成交回报。本系统不会替你下单。</div>}<button className="btn-primary mt-4 w-full justify-center py-3" disabled={!form.code || !form.name || Number(form.price) <= 0 || Number(form.quantity) <= 0} onClick={save}><Save size={15} />保存并重算当前账户</button></Modal>;
}

export function SettingsDrawer({ mode, settings, onClose, onMutate }: { mode: Mode; settings: AppSettings; onClose: () => void; onMutate: (p: Promise<Workspace>) => void }) {
  const [local, setLocal] = useState<AppSettings>(() => structuredClone(settings)); const account = local[mode]; const rec = local.reconciliation[mode];
  const patchAccount = (patch: Partial<SettingsData>) => setLocal((x) => ({ ...x, [mode]: { ...x[mode], ...patch } }));
  const patchRec = (patch: Partial<Reconciliation>) => setLocal((x) => ({ ...x, reconciliation: { ...x.reconciliation, [mode]: { ...x.reconciliation[mode], ...patch } } }));
  return <Modal title={`${mode === "real" ? "实盘" : "模拟"}账户设置`} onClose={onClose} wide><div className="space-y-5"><Card className="p-4"><h3 className="font-black text-white">账户与费用</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="初始资金" value={account.initialCash} onChange={(v) => patchAccount({ initialCash: v })} /><NumberField label="佣金费率" value={account.commissionRate} onChange={(v) => patchAccount({ commissionRate: v })} /><NumberField label="最低佣金" value={account.minCommission} onChange={(v) => patchAccount({ minCommission: v })} /><NumberField label="卖出印花税率" value={account.stampDutyRate} onChange={(v) => patchAccount({ stampDutyRate: v })} /><NumberField label="过户费率" value={account.transferFeeRate} onChange={(v) => patchAccount({ transferFeeRate: v })} /><Field label="默认备注"><input className="input" value={account.defaultRemark} onChange={(e) => patchAccount({ defaultRemark: e.target.value })} /></Field></div></Card><Card className="p-4"><h3 className="font-black text-white">同花顺期末数手工对账</h3><p className="mt-1 text-xs text-slate-500">仅用于对照展示，不读取券商、不覆盖流水。</p><label className="mt-3 flex gap-2 text-xs"><input type="checkbox" checked={rec.enabled} onChange={(e) => patchRec({ enabled: e.target.checked, updatedAt: new Date().toISOString() })} />启用对账数字</label><div className="mt-3 grid gap-3 sm:grid-cols-2"><NumberField label="总资产" value={rec.totalAssets} onChange={(v) => patchRec({ totalAssets: v })} /><NumberField label="可用现金" value={rec.availableCash} onChange={(v) => patchRec({ availableCash: v })} /><NumberField label="持仓市值" value={rec.holdingValue} onChange={(v) => patchRec({ holdingValue: v })} /><NumberField label="持仓盈亏" value={rec.holdingPnL} onChange={(v) => patchRec({ holdingPnL: v })} /><NumberField label="今日盈亏" value={rec.todayPnL} onChange={(v) => patchRec({ todayPnL: v })} /><Field label="备注"><input className="input" value={rec.remark} onChange={(e) => patchRec({ remark: e.target.value })} /></Field></div></Card><button className="btn-primary w-full justify-center py-3" onClick={() => { onMutate(request(apiPath(mode, "/settings"), { method: "PUT", body: JSON.stringify(local) })); onClose(); }}><Save size={15} />保存当前账户设置</button></div></Modal>;
}
export function Notices({ mode, items, onClose, onReload }: { mode: Mode; items: Notice[]; onClose: () => void; onReload: () => void }) {
  const act = async (url: string, init: RequestInit) => { await request(url, init); onReload(); };
  return <div className="fixed inset-0 z-50 bg-black/60" onMouseDown={onClose}><aside className="ml-auto h-full w-full max-w-lg overflow-y-auto border-l border-slate-800 bg-[#0c111b] p-5" onMouseDown={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="font-black text-white">通知中心</h2><button onClick={onClose}><X /></button></div><div className="mt-4 flex gap-2"><button className="btn" onClick={() => void act(apiPath(mode, "/notifications/read-all"), { method: "POST", body: "{}" })}>全部已读</button><button className="btn" onClick={() => void act(apiPath(mode, "/notifications"), { method: "DELETE" })}>清空</button></div><div className="mt-4 space-y-2">{!items.length ? <Empty text="暂无通知。" /> : items.map((n) => <button key={n.id} onClick={() => !n.read && void act(apiPath(mode, `/notifications/${n.id}/read`), { method: "PUT", body: "{}" })} className={`w-full rounded-xl border p-3 text-left ${n.read ? "border-slate-800 opacity-60" : "border-cyan-900 bg-cyan-950/20"}`}><b className="text-sm text-white">{n.title}</b><p className="mt-1 text-xs leading-5 text-slate-400">{n.message}</p><div className="mt-2 font-mono text-[10px] text-slate-600">{n.timestamp}</div></button>)}</div></aside></div>;
}
