import { useEffect, useState } from "react";
import { NotebookPen, Save } from "lucide-react";
import type { Review, Workspace } from "./types";
import { apiPath, money, request, today, tone } from "./lib";
import { Card, Empty, Stat } from "./ui";

export function Reviews({ workspace: w, onMutate }: { workspace: Workspace; onMutate: (p: Promise<Workspace>) => void }) {
  const [type, setType] = useState<Review["type"]>("daily"); const [date, setDate] = useState(today());
  const existing = w.reviews.find((r) => r.type === type && r.date === date);
  const [form, setForm] = useState({ planAndBasis: "", executionAndDeviation: "", resultAndEmotion: "", improvementAndNextPlan: "" });
  useEffect(() => setForm({ planAndBasis: existing?.planAndBasis || "", executionAndDeviation: existing?.executionAndDeviation || "", resultAndEmotion: existing?.resultAndEmotion || "", improvementAndNextPlan: existing?.improvementAndNextPlan || "" }), [existing?.id, type, date]);
  const patch = (key: keyof typeof form, value: string) => setForm((x) => ({ ...x, [key]: value }));
  const fields: Array<[keyof typeof form, string, string]> = [["planAndBasis", "01 计划与交易依据", "盘前计划、关注理由和真正触发交易的证据"], ["executionAndDeviation", "02 执行与纪律偏差", "实际时间、价格、数量与原计划的差异"], ["resultAndEmotion", "03 结果归因与情绪复盘", "区分方法问题、执行问题和情绪影响"], ["improvementAndNextPlan", "04 改进与下一交易日硬计划", "写可执行、可检查的时间、条件和动作"]];
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="page-title">复盘分析</h2><p className="page-sub">不复述大盘，只复盘计划、执行、结果和下一步。</p></div><div className="flex rounded-xl border border-slate-800 bg-slate-950 p-1">{(["daily", "weekly", "monthly"] as const).map((x) => <button key={x} onClick={() => setType(x)} className={`rounded-lg px-4 py-2 text-xs font-bold ${type === x ? "bg-indigo-600 text-white" : "text-slate-500"}`}>{x === "daily" ? "日复盘" : x === "weekly" ? "周复盘" : "月复盘"}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Stat label="完成轮次" value={w.reviewSummary.completedCycles} /><Stat label="胜率" value={`${w.reviewSummary.winRate.toFixed(1)}%`} /><Stat label="盈亏比" value={w.reviewSummary.profitLossRatio.toFixed(2)} /><Stat label="累计盈亏" value={`¥${money(w.account.totalPnL)}`} valueClass={tone(w.account.totalPnL)} /><Stat label="纪律执行率" value={`${w.reviewSummary.complianceRate.toFixed(1)}%`} /><Stat label="累计费用" value={`¥${money(w.reviewSummary.totalFees)}`} /></div><Card className="p-5"><div className="mb-5 flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4"><div className="flex items-center gap-2 font-black text-white"><NotebookPen size={18} className="text-indigo-400" />四段式有效复盘</div><input type="date" className="input max-w-44" value={date} onChange={(e) => setDate(e.target.value)} /></div><div className="grid gap-4 lg:grid-cols-2">{fields.map(([key, title, hint]) => <label key={key} className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"><b className="text-white">{title}</b><p className="mt-1 text-[11px] text-slate-500">{hint}</p><textarea rows={7} className="input mt-3 resize-none" value={form[key]} onChange={(e) => patch(key, e.target.value)} /></label>)}</div><button className="btn-primary mt-5 w-full justify-center py-3" onClick={() => onMutate(request(apiPath(w.mode, "/reviews"), { method: "POST", body: JSON.stringify({ id: existing?.id || `${type}-${date}`, accountMode: w.mode, type, date, ...form }) }))}><Save size={15} />保存复盘</button></Card><Card className="p-5"><h3 className="mb-4 font-black text-white">历史复盘</h3>{!w.reviews.length ? <Empty text="当前账户暂无复盘。" /> : <div className="space-y-2">{w.reviews.slice(0, 20).map((r) => <article key={`${r.accountMode}-${r.id}`} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><div className="font-mono text-xs text-indigo-300">{r.date} · {r.type}</div><p className="mt-1 line-clamp-2 text-xs text-slate-500">{r.improvementAndNextPlan || r.executionAndDeviation || r.planAndBasis || "未填写"}</p></article>)}</div>}</Card></div>;
}

