import { Bell, Plus, TrendingUp } from "lucide-react";
import type { Side, Workspace } from "./types";
import { money, tone } from "./lib";
import { Card, Empty, Stat, TradeTable } from "./ui";

export function Today({ workspace: w, onTrade }: { workspace: Workspace; onTrade: (side: Side, code?: string) => void }) {
  const a = w.account; const todayTrades = w.trades.filter((item) => item.date === a.asOfDate);
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="page-title">今日执行</h2><p className="page-sub">先处理必须行动，再看账户数字。行情查看与股票选择留在同花顺。</p></div><div className="flex gap-2"><button className="btn-primary" onClick={() => onTrade("BUY")}><Plus size={15} />记录买入</button><button className="btn-green" onClick={() => onTrade("SELL")}><TrendingUp size={15} />记录卖出</button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Stat label="总资产" value={`¥${money(a.totalAssets)}`} sub={`${a.totalReturnPct >= 0 ? "+" : ""}${a.totalReturnPct.toFixed(2)}%`} valueClass={tone(a.totalPnL)} /><Stat label="可用现金" value={`¥${money(a.availableCash)}`} sub={a.reconciliationMode ? "对账展示" : "流水推导"} /><Stat label="持仓市值" value={`¥${money(a.holdingValue)}`} sub={`${w.positions.length} 只持仓`} /><Stat label="今日盈亏" value={`¥${money(a.todayPnL)}`} valueClass={tone(a.todayPnL)} /><Stat label="今日成交" value={`${todayTrades.length} 笔`} sub={`费用 ¥${money(todayTrades.reduce((s, x) => s + x.totalFee, 0))}`} /><Stat label="纪律执行率" value={`${w.reviewSummary.complianceRate.toFixed(1)}%`} valueClass={w.reviewSummary.complianceRate >= 90 ? "text-cyan-300" : "text-amber-300"} /></div>
    <Card className="p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 font-black text-white"><Bell size={18} className="text-orange-400" />今日待执行 <span className="badge">{w.pendingActions.length}</span></div></div>{!w.pendingActions.length ? <Empty text="当前账户没有必须处理的行动。没有信号时，保持空仓也是纪律。" /> : <div className="grid gap-3 lg:grid-cols-2">{w.pendingActions.map((action) => <article key={action.id} className={`rounded-xl border p-4 ${action.priority === "danger" ? "border-rose-900 bg-rose-950/20" : action.priority === "warning" ? "border-amber-900 bg-amber-950/20" : "border-slate-800 bg-slate-950/40"}`}><div className="flex items-start justify-between gap-3"><div><b className="text-white">{action.name} <span className="font-mono text-xs text-slate-500">{action.code}</span></b><p className="mt-1 text-xs font-bold text-slate-300">{action.title}</p></div>{action.nextActionTime && <span className="badge">{action.nextActionTime}</span>}</div><p className="mt-3 text-xs leading-5 text-slate-400">{action.message}</p>{["MORNING_EXIT_DUE", "AFTERNOON_EXIT_DUE", "DEFERRED_TO_AFTERNOON"].includes(action.type) && <button className="btn-green mt-3" onClick={() => onTrade("SELL", action.code)}>记录卖出</button>}</article>)}</div>}</Card>
    <Card className="overflow-hidden"><div className="border-b border-slate-800 px-5 py-4 font-black text-white">今日成交</div><TradeTable rows={todayTrades} /></Card>
  </div>;
}

