import React, { useMemo, useState } from "react";
import { Plus, RefreshCw, Trash2 } from "lucide-react";
import type { Side, Trade, Workspace } from "./types";
import { apiPath, money, request, tone } from "./lib";
import { Card, Stat, TradeTable } from "./ui";

export function Trades({ workspace: w, onTrade, onEdit, onMutate }: { workspace: Workspace; onTrade: (side: Side) => void; onEdit: (t: Trade) => void; onMutate: (p: Promise<Workspace>) => void }) {
  const [query, setQuery] = useState(""); const [side, setSide] = useState<"ALL" | Side>("ALL");
  const rows = useMemo(() => w.trades.filter((t) => (side === "ALL" || t.type === side) && (!query || `${t.code}${t.name}`.includes(query))), [w.trades, side, query]);
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="page-title">交易记录</h2><p className="page-sub">当前账户完整流水、费用和纪律结论。</p></div><div className="flex gap-2"><button className="btn" onClick={() => onMutate(request(apiPath(w.mode, "/trades/recalculate-fees"), { method: "POST", body: "{}" }))}><RefreshCw size={14} />重算费用</button><button className="btn-primary" onClick={() => onTrade("BUY")}><Plus size={14} />买入</button><button className="btn-green" onClick={() => onTrade("SELL")}>卖出</button></div></div><div className="grid gap-3 md:grid-cols-5"><Stat label="交易笔数" value={w.reviewSummary.tradeCount} /><Stat label="完成轮次" value={w.reviewSummary.completedCycles} /><Stat label="累计费用" value={`¥${money(w.reviewSummary.totalFees)}`} /><Stat label="违规/偏差" value={w.reviewSummary.violationCount} valueClass={w.reviewSummary.violationCount ? "text-amber-300" : "text-cyan-300"} /><Stat label="累计盈亏" value={`¥${money(w.account.totalPnL)}`} valueClass={tone(w.account.totalPnL)} /></div><Card className="p-4"><div className="flex gap-3"><input className="input max-w-xs" placeholder="搜索代码或名称" value={query} onChange={(e) => setQuery(e.target.value)} /><select className="input max-w-36" value={side} onChange={(e) => setSide(e.target.value as "ALL" | Side)}><option value="ALL">全部方向</option><option value="BUY">买入</option><option value="SELL">卖出</option></select></div></Card><Card className="overflow-hidden"><TradeTable rows={rows} actions={(t) => <div className="flex gap-2"><button className="text-cyan-300" onClick={() => onEdit(t)}>编辑</button><button className="text-rose-400" onClick={() => { if (confirm(`删除 ${t.name} 的这笔交易？`)) onMutate(request(apiPath(w.mode, `/trades/${t.id}`), { method: "DELETE" })); }}><Trash2 size={14} /></button></div>} /></Card></div>;
}
