import React from "react";
import { Activity, Bell, BookOpen, BriefcaseBusiness, Clock3, History, Loader2, RefreshCw, Settings, X } from "lucide-react";
import type { Mode, Page, Trade } from "./types";
import { money, nowTime } from "./lib";

export function Sidebar({ mode, page, onMode, onPage }: { mode: Mode; page: Page; onMode: (mode: Mode) => void; onPage: (page: Page) => void }) {
  const nav: Array<[Page, string, typeof Activity, string]> = [
    ["today", "今日执行", Activity, "行动节点与风险提醒"], ["positions", "当前持仓", BriefcaseBusiness, "T+1 与尾盘处理"],
    ["trades", "交易记录", History, "当前账户完整流水"], ["reviews", "复盘分析", BookOpen, "四段式有效复盘"],
  ];
  return <aside className="hidden w-60 shrink-0 border-r border-slate-800 bg-[#0c111b] md:flex md:flex-col">
    <div className="flex h-20 items-center gap-3 border-b border-slate-800 px-5"><div className={`grid h-10 w-10 place-items-center rounded-xl font-black text-white ${mode === "real" ? "bg-orange-600" : "bg-cyan-600"}`}>TZ</div><div><div className="font-black text-white">纪律工作台</div><div className="text-[10px] tracking-widest text-slate-500">WORKSTATION V3</div></div></div>
    <div className="border-b border-slate-800 p-4"><div className="mb-2 text-[10px] font-bold tracking-widest text-slate-500">账户账本</div><div className="grid grid-cols-2 rounded-xl border border-slate-700 bg-slate-950 p-1"><button onClick={() => onMode("simulation")} className={`rounded-lg py-2 text-xs font-bold ${mode === "simulation" ? "bg-cyan-600 text-white" : "text-slate-500"}`}>模拟训练</button><button onClick={() => onMode("real")} className={`rounded-lg py-2 text-xs font-bold ${mode === "real" ? "bg-orange-600 text-white" : "text-slate-500"}`}>实盘记录</button></div></div>
    <nav className="flex-1 space-y-1 p-3">{nav.map(([key, label, Icon, sub]) => <button key={key} onClick={() => onPage(key)} className={`flex w-full items-center gap-3 rounded-xl border px-3 py-3 text-left transition ${page === key ? "border-slate-700 bg-slate-800 text-white" : "border-transparent text-slate-500 hover:bg-slate-900 hover:text-slate-200"}`}><Icon size={18} /><span><b className="block text-sm">{label}</b><small className="text-[10px] text-slate-600">{sub}</small></span></button>)}</nav>
    <div className="border-t border-slate-800 p-4 text-[10px] text-slate-500">不连接券商 · 不自动选股 · 不自动下单</div>
  </aside>;
}

export function Header({ page, mode, phase, unread, loading, onRefresh, onSettings, onNotices }: { page: Page; mode: Mode; phase: string; unread: number; loading: boolean; onRefresh: () => void; onSettings: () => void; onNotices: () => void }) {
  const title = { today: "今日执行", positions: "当前持仓", trades: "交易记录", reviews: "复盘分析" }[page];
  return <header className="flex h-20 shrink-0 items-center justify-between border-b border-slate-800 bg-[#0c111b]/95 px-5 lg:px-7"><div><div className="flex items-center gap-3"><h1 className="font-black text-white">{title}</h1><span className="badge">{phase}</span></div><p className="mt-1 text-xs text-slate-500">{mode === "real" ? "与同花顺配合，手工登记真实成交并做纪律审计" : "独立模拟账本，用于训练五日线回踩执行纪律"}</p></div><div className="flex items-center gap-2"><span className="hidden font-mono text-xs text-slate-400 sm:inline"><Clock3 size={14} className="mr-1 inline" />{nowTime()}</span><button className="icon-btn" onClick={onRefresh} title="刷新账户工作区">{loading ? <Loader2 size={17} className="animate-spin" /> : <RefreshCw size={17} />}</button><button className="icon-btn relative" onClick={onNotices}><Bell size={17} />{unread > 0 && <i className="absolute -right-1 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-orange-600 px-1 text-[9px] font-black text-white">{unread}</i>}</button><button className="icon-btn" onClick={onSettings}><Settings size={17} /></button></div></header>;
}

export function Loading() { return <div className="grid h-72 place-items-center rounded-2xl border border-slate-800 bg-slate-900/50 text-sm text-slate-500"><span className="flex items-center gap-2"><Loader2 className="animate-spin" size={18} />正在加载当前账户……</span></div>; }
export function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-800 bg-[#101722] shadow-xl shadow-black/10 ${className}`}>{children}</section>; }
export function Stat({ label, value, sub, valueClass = "text-white" }: { label: string; value: string | number; sub?: string; valueClass?: string }) { return <Card className="p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</div><div className={`mt-2 font-mono text-xl font-black ${valueClass}`}>{value}</div>{sub && <div className="mt-1 text-[10px] text-slate-600">{sub}</div>}</Card>; }
export function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-slate-700 p-10 text-center text-sm text-slate-500">{text}</div>; }

export function Mini({ label, value, cls = "text-white" }: { label: string; value: string | number; cls?: string }) { return <div className="rounded-lg border border-slate-800 bg-slate-950/50 p-3"><div className="text-[10px] text-slate-600">{label}</div><div className={`mt-1 font-mono font-bold ${cls}`}>{value}</div></div>; }

export function TradeTable({ rows, actions }: { rows: Trade[]; actions?: (trade: Trade) => React.ReactNode }) { if (!rows.length) return <Empty text="暂无符合条件的交易记录。" />; return <div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left text-xs"><thead className="bg-slate-950 text-slate-500"><tr>{["日期时间", "方向", "股票", "价格", "数量", "金额", "费用", "纪律结论", "标签", "操作"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((t) => <tr key={`${t.accountMode}-${t.id}`} className="border-t border-slate-800 hover:bg-slate-900/60"><td className="px-4 py-3 font-mono">{t.date} {t.time}</td><td className={`px-4 py-3 font-black ${t.type === "BUY" ? "text-rose-400" : "text-emerald-400"}`}>{t.type === "BUY" ? "买入" : "卖出"}</td><td className="px-4 py-3"><b className="text-white">{t.name}</b><div className="font-mono text-slate-600">{t.code}</div></td><td className="px-4 py-3 font-mono">{t.price.toFixed(2)}</td><td className="px-4 py-3 font-mono">{t.quantity}</td><td className="px-4 py-3 font-mono">{money(t.amount)}</td><td className="px-4 py-3 font-mono">{money(t.totalFee)}</td><td className="px-4 py-3"><span className="badge">{t.rulesConclusion}</span></td><td className="max-w-48 px-4 py-3 text-slate-500">{t.violationTags.join("、") || "—"}</td><td className="px-4 py-3">{actions?.(t)}</td></tr>)}</tbody></table></div>; }

export function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (v: number) => void }) { return <Field label={label}><input type="number" step="any" className="input" value={value} onChange={(e) => onChange(Number(e.target.value))} /></Field>; }
export function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs text-slate-500">{label}<div className="mt-1.5">{children}</div></label>; }

export function Modal({ title, onClose, children, wide = false }: { title: string; onClose: () => void; children: React.ReactNode; wide?: boolean }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" onMouseDown={onClose}><div className={`max-h-[92vh] w-full overflow-y-auto rounded-2xl border border-slate-700 bg-[#0c111b] shadow-2xl ${wide ? "max-w-3xl" : "max-w-xl"}`} onMouseDown={(e) => e.stopPropagation()}><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><h2 className="font-black text-white">{title}</h2><button onClick={onClose}><X /></button></div><div className="space-y-4 p-5">{children}</div></div></div>; }
